# Generated by Django 3.2.8 on 2021-11-05 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trainer', '0001_initial'),
        ('Tracking', '0001_initial'),
        ('Courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('bmi', models.FloatField(default=0)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_trainer', models.BooleanField(default=False)),
                ('owned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study', to='Courses.course')),
                ('track_customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks_owner', to='Tracking.tracks')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_trainer', to='Trainer.trainer')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
