# Generated by Django 3.2.8 on 2021-10-16 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('tr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('specialist', models.CharField(max_length=50)),
                ('teach', models.ManyToManyField(related_name='teach', to='Users.Course')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='Users.course')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='Users.trainer')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
