# Generated by Django 3.2.8 on 2021-10-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='teach',
        ),
        migrations.AddField(
            model_name='course',
            name='teach',
            field=models.ManyToManyField(related_name='teach', to='Users.Trainer'),
        ),
    ]
