# Generated by Django 3.2.8 on 2021-10-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
        ('Users', '0002_alter_customer_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='owned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_trainer', to='Users.trainer'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
