# Generated by Django 3.2.7 on 2021-11-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_alter_tracks_track_trainer'),
        ('Users', '0002_auto_20211106_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='track_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks_owner', to='Tracking.tracks'),
        ),
    ]
