# Generated by Django 3.2.8 on 2021-11-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0006_alter_tracks_track_trainer'),
        ('Users', '0003_alter_customer_track_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='track_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks_owner', to='Tracking.tracks'),
        ),
    ]
