# Generated by Django 3.2.8 on 2021-11-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0005_delete_book'),
        ('Users', '0004_alter_customer_track_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Harassment', 'harassment'), ('Bad word', 'use bad word'), ('Threaten', 'threaten'), ('Hate speeches', 'hate speeches'), ('Not helpful', 'advice not helpful')], max_length=30)),
                ('context', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_trainer', to='Trainer.trainer')),
            ],
        ),
    ]
