# Generated by Django 3.2.8 on 2021-10-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
