# Generated by Django 3.2.8 on 2021-11-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_auto_20211105_2045'),
        ('Users', '0006_auto_20211031_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='track_customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks_owner', to='Tracking.tracks'),
        ),
    ]
