# Generated by Django 3.2.6 on 2021-11-04 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0002_auto_20211105_0051'),
        ('Users', '0006_auto_20211031_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_track', to='Workout.tracks'),
        ),
    ]
