# Generated by Django 3.2.8 on 2021-11-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_report_report_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportby', to='Users.customer'),
        ),
    ]
