# Generated by Django 3.2.6 on 2021-11-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0002_auto_20211105_0051'),
        ('Users', '0007_customer_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='track',
        ),
        migrations.AddField(
            model_name='customer',
            name='track',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_track', to='Workout.Tracks'),
        ),
    ]
