# Generated by Django 3.2.8 on 2021-11-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_report_report_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_default_pic.jfif', null=True, upload_to=''),
        ),
    ]
