# Generated by Django 3.2.6 on 2021-11-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0003_auto_20211105_0110'),
        ('Users', '0008_auto_20211105_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='track',
        ),
        migrations.AddField(
            model_name='customer',
            name='track',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_track', to='Workout.tracks'),
        ),
    ]
