# Generated by Django 3.2.8 on 2021-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_news_ps'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
