# Generated by Django 3.2.8 on 2021-11-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('specialist', models.CharField(max_length=100)),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
    ]
