# Generated by Django 3.2.8 on 2021-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0002_auto_20211106_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
