# Generated by Django 3.2.8 on 2021-11-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0003_trainer_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.IntegerField(choices=[(0, '04:00 – 06:00'), (1, '06:30 – 08:30'), (2, '09:00 – 11:00'), (3, '12:00 – 14:00'), (4, '15:00 – 17:00'), (5, '18:00 – 20:00'), (6, '21:00 – 23:00')])),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainer.trainer')),
            ],
            options={
                'unique_together': {('trainer', 'timeslot')},
            },
        ),
    ]
