# Generated by Django 3.2.8 on 2021-11-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
