# Generated by Django 3.2.8 on 2021-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0005_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='contract_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
