# Generated by Django 3.2.8 on 2021-11-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0006_trainer_contract_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='contract_link',
            new_name='videocall_link',
        ),
    ]
