# Generated by Django 3.2.8 on 2021-11-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0007_rename_contract_link_trainer_videocall_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='videocall_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
