# Generated by Django 3.2.6 on 2021-11-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0006_auto_20211031_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_date', models.DateField(blank=True)),
                ('dp_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_name', models.CharField(max_length=500)),
                ('bd_part', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_set', models.CharField(max_length=500)),
                ('wo_time', models.CharField(max_length=500)),
                ('wo_status', models.BooleanField(default=False)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='Workout.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_program_status', models.BooleanField(default=False)),
                ('day_pragram', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Workout.day_program')),
                ('track_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='Users.customer')),
                ('track_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='Users.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='day_program',
            name='workouts',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Workout.workout'),
        ),
    ]
