# Generated by Django 3.2.6 on 2021-11-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20211105_0108'),
        ('Workout', '0002_auto_20211105_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='track_customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='Users.customer'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='Users.trainer'),
        ),
    ]
