# Generated by Django 3.2.6 on 2021-11-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0003_auto_20211105_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='track_customer',
        ),
    ]
