# Generated by Django 3.2.8 on 2021-11-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0004_remove_tracks_track_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_program',
            name='workouts',
        ),
        migrations.AddField(
            model_name='day_program',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='workoutplan', to='Workout.Workout'),
        ),
    ]
