# Generated by Django 3.2.8 on 2021-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_alter_customer_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=500)),
                ('teach', models.ManyToManyField(related_name='teacher', to='Users.Trainer')),
            ],
        ),
    ]
