# Generated by Django 3.2.8 on 2021-11-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=500)),
                ('days', models.PositiveIntegerField(default=0)),
                ('teach', models.ManyToManyField(related_name='teacher', to='Trainer.Trainer')),
            ],
        ),
    ]
