# Generated by Django 3.2.8 on 2021-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teach',
            field=models.ManyToManyField(related_name='teacher', to='Users.Trainer'),
        ),
    ]
