# Generated by Django 3.2.8 on 2021-11-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
