# Generated by Django 3.2.8 on 2021-11-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_course_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pic',
            field=models.ImageField(blank=True, default='default-image.png', null=True, upload_to=''),
        ),
    ]
