# Generated by Django 3.2.8 on 2021-11-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customer_track_customer'),
        ('Trainer', '0005_delete_book'),
        ('Courses', '0012_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trainer.trainer'),
        ),
    ]
