# Generated by Django 3.2.8 on 2021-11-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0014_auto_20211112_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '04:00 – 05:30'), (1, '06:00 – 07:30'), (2, '08:00 – 09:30'), (3, '10:00 – 11:30'), (4, '13:00 – 14:30'), (5, '15:00 – 16:30'), (6, '17:00 – 18:30'), (7, '19:00 – 20:30'), (8, '21:00 – 22:30'), (9, '23:00 – 01:30')]),
        ),
    ]
