# Generated by Django 3.2.8 on 2021-11-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0005_delete_book'),
        ('Courses', '0015_alter_appointment_timeslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('trainer', 'date', 'timeslot')},
        ),
    ]
