# Generated by Django 3.2.8 on 2021-11-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0005_delete_book'),
        ('Users', '0003_alter_customer_track_customer'),
        ('Courses', '0016_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('trainer', 'date', 'timeslot', 'customer')},
        ),
    ]
