# Generated by Django 3.2.8 on 2021-11-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0017_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'timeslot')},
        ),
    ]
