# Generated by Django 3.2.8 on 2021-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0022_alter_appointment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.TextField(choices=[('04:00 – 05:30', '04:00 – 05:30'), ('06:00 – 07:30', '06:00 – 07:30'), ('08:00 – 09:30', '08:00 – 09:30'), ('10:00 – 11:30', '10:00 – 11:30'), ('13:00 – 14:30', '13:00 – 14:30'), ('15:00 – 16:30', '15:00 – 16:30'), ('17:00 – 18:30', '17:00 – 18:30'), ('19:00 – 20:30', '19:00 – 20:30'), ('21:00 – 22:30', '21:00 – 22:30'), ('23:00 – 01:30', '23:00 – 01:30')]),
        ),
    ]
