# Generated by Django 3.2.8 on 2021-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
