# Generated by Django 3.2.8 on 2021-11-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0006_auto_20211031_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('parts', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reps', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracking.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_program_status', models.BooleanField(default=False)),
                ('maxday', models.PositiveIntegerField(default=5)),
                ('day_pragram', models.ManyToManyField(blank=True, related_name='daily', to='Tracking.Program')),
                ('track_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_owner', to='Users.customer')),
                ('track_trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='Users.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='objective',
            field=models.ManyToManyField(related_name='workout', to='Tracking.Workout'),
        ),
        migrations.AddField(
            model_name='program',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.customer'),
        ),
    ]
