# Generated by Django 3.2.8 on 2021-11-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ManyToManyField(blank=True, to='Tracking.Exercise'),
        ),
    ]
