# Generated by Django 3.2.8 on 2021-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='maxday',
        ),
        migrations.AddField(
            model_name='tracks',
            name='day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
