# Generated by Django 3.2.8 on 2021-11-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tracking', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='track_trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='Users.trainer'),
        ),
        migrations.AddField(
            model_name='program',
            name='objective',
            field=models.ManyToManyField(related_name='workout', to='Tracking.Workout'),
        ),
    ]
