# Generated by Django 3.2.8 on 2021-11-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
        ('Tracking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='Trainer.trainer'),
        ),
    ]
