# Generated by Django 3.2.8 on 2021-11-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0002_auto_20211104_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='track_customer',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
    ]
