# Generated by Django 3.2.8 on 2021-11-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_auto_20211104_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='objective',
        ),
        migrations.AddField(
            model_name='program',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracking.workout'),
        ),
    ]
