# Generated by Django 3.2.6 on 2021-11-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0003_trainer_profile_pic'),
        ('Tracking', '0003_alter_tracks_track_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='Trainer.trainer'),
        ),
    ]
