# Generated by Django 3.2.8 on 2021-11-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0005_delete_book'),
        ('Tracking', '0005_alter_tracks_track_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer', to='Trainer.trainer'),
        ),
    ]
