# Generated by Django 3.2.8 on 2021-11-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0005_workout_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='objective',
        ),
        migrations.AddField(
            model_name='program',
            name='objective',
            field=models.ManyToManyField(null=True, related_name='workout', to='Tracking.Workout'),
        ),
    ]
