# Generated by Django 3.2.8 on 2021-11-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0006_alter_tracks_track_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='day_pragram',
            new_name='day_program',
        ),
        migrations.AddField(
            model_name='program',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
