# Generated by Django 3.2.8 on 2021-11-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0006_auto_20211104_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='objective',
            field=models.ManyToManyField(related_name='workout', to='Tracking.Workout'),
        ),
    ]
