# Generated by Django 3.2.8 on 2021-11-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20211031_1818'),
        ('Tracking', '0007_alter_program_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='owner',
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_program_status', models.BooleanField(default=False)),
                ('day_pragram', models.ManyToManyField(blank=True, related_name='daily', to='Tracking.Program')),
                ('track_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_owner', to='Users.customer')),
                ('track_trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='Users.trainer')),
            ],
        ),
    ]
