# Generated by Django 3.2.8 on 2021-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0007_auto_20211113_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
