# Generated by Django 3.2.8 on 2021-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0008_program_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
