# Generated by Django 3.2.8 on 2021-11-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_days'),
        ('Tracking', '0008_auto_20211104_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='maxday',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
        ),
    ]
