# Generated by Django 3.2.8 on 2021-11-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_days'),
        ('Tracking', '0009_tracks_maxday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='maxday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
        ),
    ]
