# Generated by Django 3.2.8 on 2021-11-14 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0009_alter_tracks_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
